# Generated by Django 4.2.13 on 2024-06-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('subcategory', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='images/images')),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
